# NumPy: Numerical Python

NumPy is a Python library that makes it easy to work with numbers and do math with large sets of data, especially using arrays (like lists of numbers). It's super fast and great for things like science, engineering, and data analysis.

In [7]:
import numpy as np

## Summary

- Array Creation
- Array Manipulation
- Array Inspection
- Indexing and Filtering
- Math Operations
- Random
- Statistics
- Set Operations

## Array Creation

### np.array(object)

- Creates a NumPy array from a list.
- Converts a regular Python list into a NumPy array. Enables vectorized operations and methods.

In [14]:
np.array([1, 2, 3])

array([1, 2, 3])

### np.zeros(shape, dtype=float)

- Creates an array filled with zeros.
- Returns a (X)x(Y) array of zeros. Useful for initialization.

In [17]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

### np.ones(shape, dtype=float)

- Creates an array filled with ones.
- Similar to zeros, but filled with ones.

In [23]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.full(shape, fill_value)

- Creates an array with a constant value.
- Fills the entire array with the given number.

In [25]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

### np.arange(start, stop, step)

- Array of evenly spaced values.
- Like Python’s range() but returns a NumPy array.

In [29]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### np.linspace(start, stop, num)

- Evenly spaced values over interval
- Returns 5 values between 0 and 1 including both ends.

In [32]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### np.random.rand(shape)

- Random numbers from uniform dist.
-  Useful for simulations or initializing weights.

In [35]:
np.random.rand(2, 2)

array([[0.18970959, 0.25992134],
       [0.35697874, 0.82068057]])

### np.random.randint(low, high, size)

- Random integers in a range
- Creates a 2x2 array with random integers from 0 to 9 :

In [58]:
np.random.randint(1, 10, (2, 2))

array([[3, 4],
       [6, 7]])

## Array Manipulation

### array.reshape(new_shape)
- Changes the shape of an array without changing its data.

arr = np.arange(6)
reshaped = arr.reshape((2, 3))

print(f"Original array: {arr}")
print(f"Reshaped array: {reshaped}")

### array.flatten()
- Flattens a multi-dimensional array into a 1D array.

In [27]:
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()

print(f"Original array: {arr}")
print(f"Flatten array: {flat}")

Original array: [[1 2]
 [3 4]]
Flatten array: [1 2 3 4]


**Explanation**: Converts [[1, 2], [3, 4]] into [1, 2, 3, 4]. Always returns a copy

### array.reval()
- Also flattens an array, but returns a view when possible (more memory efficient).

In [30]:
arr = np.array([[1, 2], [3, 4]])
r = arr.ravel()

print(f"Original array: {arr}")
print(f"Ravel array: {r}")

Original array: [[1 2]
 [3 4]]
Ravel array: [1 2 3 4]


**Explanation**: Works like flatten() but doesn't copy data unless needed.

### array.transpose()  __OR__  array.T
- Swaps the axes of the array (i.e., rows become columns).


In [39]:
arr = np.array([[1, 2], [3, 4]])
transposed = arr.T

print(f"Original array: {arr}")
print(f"Transposed array: {transposed}")

Original array: [[1 2]
 [3 4]]
Transposed array: [[1 3]
 [2 4]]


**Explanation**: Converts: [[1, 2],[3, 4]]  __into__  [[1, 3], [2, 4]]

### array.resize(new_shape)
- Changes the shape of an array in-place

In [46]:
arr = np.array([1, 2, 3, 4])
print(f"Original array: {arr}")

arr.resize((2, 2))
print(f"Resized array {arr}")

Original array: [1 2 3 4]
Resized array [[1 2]
 [3 4]]


**Explanation**: Unlike reshape(), this modifies the original array and can fill with garbage values if not enough data.

### np.concatenate((a1, a2), axis=0)
- Combines multiple arrays along an axis.
- Merges two arrays vetrically

In [50]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])
result = np.concatenate((a, b), axis=0)

result

array([[1, 2],
       [3, 4]])

### np.stack((a1, a2), axis=0)
- Stacks arrays along a new axis
- Creates a new dimension

In [58]:
a = np.array([1, 2])
b = np.array([3, 4])
np.stack((a, b), axis=0)

array([[1, 2],
       [3, 4]])

### np.vstack __AND__ np.hstack()
- ertical and horizontal stacking shortcuts.

In [66]:
a = np.array([1, 2])
b = np.array([3, 4])

print(f"Vertical: {np.vstack((a, b))}")
print(f"Horizontal: {np.hstack((a, b))}")


Vertical: [[1 2]
 [3 4]]
Horizontal: [1 2 3 4]


In [ ]:
### np.split() __OR__ np.array_split()
- Splits array into multiple sub-